{{- if and (not .Values.freshservice.existingSecret) .Values.freshservice.apiKey .Values.freshservice.domain }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freshservice-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freshservice-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.freshservice.apiKey | quote }}
  domain: {{ .Values.freshservice.domain | quote }}
{{- end }}
