{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "freshservice-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "freshservice-exporter.labels" . | nindent 4 }}
{{- end }}
